### ISSUE TITLE
[feature equest]Prevent multiple runs in a short period of time

### ISSUE THREAD

**Issue by uuRRx0** [neotan/vscode-auto-restart-typescript-eslint-servers#9]
When compiling, the files in the folder will be created multiple times. Is it possible to add a mechanism to make the program run less frequently?

My setting config is `**/{tsconfig,.umi/**/*}.{json,app.json,app.js,js,ts}`

**Comment by neotan** [comment]
Thanks for raising the issue, @uuRRx0 !
Monitoring the designated config files frequently is the core idea to make sure they come into effect timely.

Wanted to confirm if the restarting notifications at the lower are bottom disturbing you, they can be disabled by setting `showRestartNotificationForESLint: false` and `"autoRestart.showRestartNotificationForTypescript": false`. Or u may specify the actual paths to the expectant config files only (I know that would be a bit too annoying...). 

Hope these options help🍻!

**Comment by neotan** [comment]
Close it as no response, feel free reopen if needed.

**Comment by waynesbrain** [comment]
I was looking for a solution to this today and I was wondering if there was some sort of `delay` or `debounce` that I could set. The notifications aren't my issue, but I have a monorepo in a `code-workspace` file with lots of local dependencies and restarting the TS server many times in a row is a bit jarring - vs code editors all flicker as the Intellisense turns off and on.

The `debounce` solution seems like a natural thing to implement here since I don't think anyone wants to restart 10 times in a row within ~500 milliseconds but rather just once after the ~500ms has passed, after the last change was detected.
